import { Component } from '@angular/core';

@Component({
	selector: 'app-root',
	template: `
		<ion-content>
			<!-- Note: ion-content creates the main, scrollable view of the application -->

			<router-outlet>
				<!-- router outlet switches between tasks -->

				<!--ion-popover-->

					<!--task-detail-->
						<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * -->
						<!-- 'task-detail' displays the details of a single task -->
						<!--   (  see  'app/tasks/task-detail.component.ts'  )   -->
						<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * -->
					<!--/task-detail-->

				<!--/ion-popover-->

			</router-outlet>

			<task-list>
				<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
				<!-- 'task-list' is list of tasks in any kind of context i.e. different groups -->
				<!--               (  see  'app/tasks/task-list.component.ts'  )               -->
				<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
			</task-list>

		</ion-content>
	`,
	styles: []
})
export class AppComponent
{
	title= 'WillDo';
}



import { Type } from '@angular/core';
import { Location } from '@angular/common';
import { PopoverController, ModalController } from '@ionic/angular';
/** Loads the given component in a context most friendly for the current screen */
export class DynamicView
{
	/** retrieves or generates a dynamic view of this component */
	static get(componentClass: Type<any>): Type<any> {
		var base= this.map.get(componentClass);
		if ( ! base )
			this.map.set(componentClass, base= this.generate(componentClass));
		return base;
	}

	private static generate(component: Type<any>) {
		@Component({template:``})
		class dynamicClass
		{
			constructor(
				private location: Location,
				private modalController: ModalController
			)
			{
				this.showInModal();
			}

			private async showInModal()
			{
				const modal= await this.modalController.create( { component: component} );
				modal.present(); // show the model
				modal.onWillDismiss().then( () => this.location.back() ); // go backwards when the view is close
			}
		}
		return dynamicClass;
	}

	/** retrieves all the components given to this class to be placed in a dynamic context */
	public static getUserComponents(): Type<any>[] {
		return Array.from( this.map.keys() );
	}

	/** retrieves all dynamic views generated by this class */
	public static getGeneratedComponents(): Type<any>[] {
		return Array.from( this.map.values() );
	}

	/** stores the components used by and generated by DynamicView  */
	private static readonly map= new Map< Type<any>, Type<any> >();
}